/*VOLVER TODO A CERO, BORRAR BASE DE DATOS Y USUARIO (SE DEBERÍA EJECUTAR COMO ROOT)*/
REVOKE ALL PRIVILEGES, GRANT OPTION FROM 'academic_user'@'localhost';
DROP USER IF EXISTS 'academic_user'@'localhost';
DROP DATABASE IF EXISTS academic_db;